runtime: python39

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  GAE_ENV: 'standard'

handlers:
  - url: /static
    static_dir: static/
  - url: /.*  # This routes everything to the backend
    script: auto
